package com.telerikacademy.web.deliver_it.controllers.mvc;

import java.util.List;

public abstract class Constants {
    public static final String BASE_URL = "/";
    public static final String GET_BY_ID_URL = "/{id}";
    public static final String GET_BY_NAME_URL = "/name";
    public static final String CREATE_URL = "/new";
    public static final String UPDATE_URL = "/{id}/update";
    public static final String DELETE_URL = "/{id}/delete";
    public static final String LOGIN_URL = "/login";
    public static final String LOGOUT_URL = "/logout";
    public static final String WAREHOUSES_URL = "/warehouses";
    public static final String SHIPMENTS_URL = "/shipments";
    public static final String PARCELS_URL = "/parcels";
    public static final String SORTED_URL = "/sorted";
    public static final String EMPLOYEES_URL = "/employees";
    public static final String FILTER_WEIGHT_URL = "/filter/weight";
    public static final String NEXT_SHIPMENT_TO_WAREHOUSE_URL = "/warehouses/{id}/next";
    public static final String SHIPMENTS_TO_WAREHOUSE_URL = "/warehouses/{id}";
    public static final String SHIPMENTS_BY_USER_URL = "/users/{id}";
    public static final String PARCEL_ADDITIONAL_INFO_URL = "/{id}/additionalInfo";
    public static final String FILTER_BY_STATUS_URL = "/filter/status";

    public static final String WAREHOUSE_ATTRIBUTE = "warehouse";
    public static final String WAREHOUSES_ATTRIBUTE = "warehouses";
    public static final String WAREHOUSES_BY_COUNTRY_ATTRIBUTE = "warehousesByCountry";
    public static final String PARCEL_ATTRIBUTE = "parcel";
    public static final String PARCEL_CATEGORIES_ATTRIBUTE = "parcelCategories";
    public static final String PARCEL_SORTING_DTO_ATTRIBUTE = "parcelSortingDto";
    public static final String SORTING_TYPES_ATTRIBUTE = "sortingTypes";
    public static final String PARCELS_DTO_OUT_SORTING_RESULT_ATTRIBUTE = "sortingResult";
    public static final String PARCELS_ATTRIBUTE = "parcels";
    public static final String SHIPMENT_ATTRIBUTE = "shipment";
    public static final String CURRENT_DATE = "currentDate";
    public static final String SHIPMENT_STATUSES = "shipmentStatuses";
    public static final String SHIPMENTS_ATTRIBUTE = "shipments";
    public static final String ADDRESS_ATTRIBUTE = "address";
    public static final String ADDRESSES_ATTRIBUTE = "addresses";
    public static final String CUSTOMER_ATTRIBUTE = "customer";
    public static final String CUSTOMER_DTO_ATTRIBUTE = "customerDto";
    public static final String EMPLOYEE_ATTRIBUTE = "employee";
    public static final String EMPLOYEE_DTO_ATTRIBUTE = "employeeDto";
    public static final String CUSTOMERS_ATTRIBUTE = "customers";
    public static final String CITY_ATTRIBUTE = "city";
    public static final String CITIES_ATTRIBUTE = "cities";
    public static final String COUNTRY_ATTRIBUTE = "country";
    public static final String COUNTRIES_ATTRIBUTE = "countries";
    public static final String COUNTRIES_WITH_WAREHOUSE_ATTRIBUTE = "countriesWithWarehouse";
    public static final String WEIGHT_UNITS_ATTRIBUTE = "weightUnits";
    public static final String FILTER_BY_COUNTRY_ATTRIBUTE = "filterByCountry";
    public static final String ERROR_ATTRIBUTE = "error";
    public static final String WEIGHT_FILTER_DTO_ATTRIBUTE = "filterByWeightDto";

    public static final String WAREHOUSE_VIEW = "warehouse-by-id";
    public static final String WAREHOUSE_CREATE_VIEW = "warehouse-create";
    public static final String WAREHOUSE_UPDATE_VIEW = "warehouse-update";
    public static final String WAREHOUSE_DELETE_VIEW = "warehouse-delete";
    public static final String WAREHOUSES_VIEW = "warehouses";
    public static final String PARCEL_VIEW = "parcel-by-id";
    public static final String PARCEL_CREATE_VIEW = "parcel-create";
    public static final String PARCEL_UPDATE_VIEW = "parcel-update";
    public static final String PARCEL_DELETE_VIEW = "parcel-delete";
    public static final String PARCELS_SORTED_VIEW = "parcels-sorted";
    public static final String FILTER_BY_STATUS_VIEW = "parcels-by-status";
    public static final String SORTED_RESULT_VIEW = "parcels-sorted-result";
    public static final String SHIPMENT_NEXT_VIEW = "shipment-next";
    public static final String SHIPMENT_BY_ID_VIEW = "shipment-by-id";
    public static final String SHIPMENT_BY_WAREHOUSE_VIEW = "shipments-by-warehouse";
    public static final String SHIPMENT_BY_USER_VIEW = "shipments-by-user";
    public static final String SHIPMENT_CREATE_VIEW = "shipment-create";
    public static final String SHIPMENT_UPDATE_VIEW = "shipment-update";
    public static final String SHIPMENT_DELETE_VIEW = "shipment-delete";
    public static final String CUSTOMER_VIEW = "customer";
    public static final String EMPLOYEE_CREATE_VIEW = "employee-create";
    public static final String EMPLOYEE_UPDATE_VIEW = "employee-update";
    public static final String EMPLOYEE_DELETE_VIEW = "employee-delete";
    public static final String CUSTOMER_CREATE_VIEW = "customer-create";
    public static final String CUSTOMER_UPDATE_VIEW = "customer-update";
    public static final String CUSTOMER_DELETE_VIEW = "customer-delete";
    public static final String CUSTOMER_BY_ID_VIEW = "customer-by-id";
    public static final String CUSTOMERS_VIEW = "customers";
    public static final String CITY_VIEW = "city";
    public static final String CITIES_VIEW = "cities";
    public static final String CITY_BY_ID_VIEW = "city-by-id";
    public static final String COUNTRY_VIEW = "country";
    public static final String COUNTRIES_VIEW = "countries";
    public static final String COUNTRY_BY_ID_VIEW = "country-by-id";
    public static final String LOGIN_VIEW = "login";
    public static final String INDEX_VIEW = "index";
    public static final String PARCELS_FILTERED_BY_WEIGHT_VIEW = "parcels-by-weight";
    public static final String EMPLOYEE_BY_ID_VIEW = "employee-by-id";
    public static final String SHIPMENTS_INDEX_VIEW = "shipments-index";

    public static final String ACCESS_DENIED = "access-denied";
    public static final String NOT_FOUND_VIEW = "error";

    public static final String CREDENTIALS = "credentials";
    public static final String LAST_NAME = "userLastName";
    public static final String IS_LOGGED = "isLogged";
    public static final String NUMBER_OF_CUSTOMERS = "numberOfCustomers";
    public static final String ASCENDING = "Ascending";
    public static final String DESCENDING = "Descending";
    public static final String SORTING_TYPE_ANY = "any";
    public static final String SORTING_TYPE_ASCENDING = "ASC";
    public static final String SORTING_TYPE_DESCENDING = "DES";
    public static final String NONE = "None";
    public static final List<String> SORTING_TYPES_NAMES = List.of(NONE, ASCENDING, DESCENDING);

    public static final String FILTER_BY_STATUS_ATTRIBUTE = "filterByStatusDto";
    public static final String ROLE = "role";
    public static final String BY_ID = "by-id";
    public static final String CUSTOMER_SEARCH_DTO = "customerSearchDto";
    public static final String ID_DTO = "idDto";
    public static final String BY_USER = "by-user";
    public static final String TO_WAREHOUSE = "to-warehouse";
    public static final String NEXT_TO_WAREHOUSE = "next-to-warehouse";
    public static final String UPDATE_ID = "update-id";

    public static final List<String> SHIPMENT_OPTIONS  = List.of(BY_ID, BY_USER, TO_WAREHOUSE, NEXT_TO_WAREHOUSE);
    public static final List<String> EMPLOYEE_OPTIONS  = List.of(BY_ID, UPDATE_ID);
    public static final String EMPLOYEE_INDEX_VIEW = "employee-index";
}
